name: ai_wellbeing
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
      - accelerate
      - datasets
      - einops
      - hf-transfer
      - huggingface-hub
      - jinja2
      - matplotlib
      - numpy
      - openai
      - pandas
      - protobuf
      - pydantic
      - safetensors
      - scikit-learn
      - scipy
      - seaborn
      - sentencepiece
      - tqdm
      - transformers
